### ISSUE TITLE
Document process for generating resources

### ISSUE THREAD

**Issue by dethrace-labs** [yuv422/skifree_decomp#1]
Any chance of creating a script to pull the resources from the executable and put them in the right places to create a build?

Also - is WinXP required to build it, or is it just what you used while reversing?

**Comment by yuv422** [comment]
I've just updated the readme with the steps I used to extract the resources. :)
You don't need to use XP. Anything that runs Visual Studio 6 should be fine.

**Comment by dethrace-labs** [comment]
Thanks!
