### ISSUE TITLE
Asking for permission to include your work.

### ISSUE THREAD

**Issue by FRDS** [yuv422/skifree_decomp#2]
Dear, yuv422.

I just stumbled upon your repository, and I'm interested in including your work in my [Collaborative Decomp Watch List](http://cs.google.com/spreadsheets/d/e/2PACX-1vRL-uMdfMnxkp0dPZ8Ovum93fv4Pguv2h_YprXAEdkAcvcIwyRbj3hwlvECm3QwLHWrwN5yS3ElIeKT/pubhtml) project. Therefore, I wish to ask your permission.

This list is meant to document projects for visibility (such as to avoid duplicate projects) and facilitate collaborative efforts. This list **will only be used internally within the reverse-engineering scene** and not be **published for the general audience**.

Thank you in advance for considering my request.
_Best regards._

**Comment by yuv422** [comment]
Sure, sounds good to me. :)

**Comment by FRDS** [comment]
> Sure, sounds good to me. :)

Great! Thank you for your cooperation. By the way, do you want to edit it yourself? I can send you an editable link, though I might need to share it through some discreet means.
